import type { RealtimeChannel, SupabaseClient } from "@supabase/supabase-js";
import {
  TransientAiError,
  PermanentAiError,
  classifyError,
  fetchCurrentCanvas,
} from "./design-agent.ts";

declare const Deno: any;

export interface SpecTaskContext {
  runId: string;
  projectId: string;
  userId: string;
  input: {
    roomId?: string;
    chatHistory?: unknown[];
    nodes?: unknown[];
    edges?: unknown[];
    [key: string]: unknown;
  };
  signal: AbortSignal;
}

export const SPECS_BUCKET = "specs";
const OPENROUTER_MODEL_ID = "nvidia/nemotron-3.5-lightning:free";

function getOpenRouterApiKey(): string | null {
  if (typeof Deno !== "undefined" && Deno?.env?.get) {
    const envVal = Deno.env.get("OPENROUTER_API_KEY");
    if (envVal && envVal.trim()) return envVal.trim();
  }

  if (typeof process !== "undefined" && process?.env?.OPENROUTER_API_KEY) {
    const envVal = process.env.OPENROUTER_API_KEY;
    if (envVal && envVal.trim()) return envVal.trim();
  }

  return null;
}

async function sendAiStatus(
  channel: RealtimeChannel | null,
  statusPayload: {
    runId: string;
    projectId: string;
    status: "queued" | "running" | "retrying" | "completed" | "failed";
    step: "start" | "analyzing" | "generating" | "complete" | "failed";
    message: string;
    text?: string;
  }
): Promise<void> {
  if (!channel) return;
  try {
    await channel.send({
      type: "broadcast",
      event: "ai-status",
      payload: {
        ...statusPayload,
        kind: "spec",
        timestamp: new Date().toISOString(),
      },
    });
  } catch (err) {
    console.warn("[generate-spec] Failed to broadcast ai-status:", err);
  }
}

export function cleanMarkdownSpec(rawText: string): string {
  let text = rawText.trim();
  // Strip <think>...</think> reasoning blocks if generated by reasoning models
  text = text.replace(/<think>[\s\S]*?<\/think>/gi, "").trim();

  // Strip wrapping markdown code blocks if the entire response is enclosed in ```markdown ... ```
  if (text.startsWith("```markdown") && text.endsWith("```")) {
    text = text.slice("```markdown".length, text.length - 3).trim();
  } else if (text.startsWith("```md") && text.endsWith("```")) {
    text = text.slice("```md".length, text.length - 3).trim();
  } else if (text.startsWith("```") && text.endsWith("```")) {
    text = text.slice(3, text.length - 3).trim();
  }

  return text;
}

export async function generateSpecWithOpenRouter(
  projectName: string,
  nodes: unknown[],
  edges: unknown[],
  chatHistory: unknown[],
  signal: AbortSignal
): Promise<string> {
  const openRouterApiKey = getOpenRouterApiKey();
  if (!openRouterApiKey) {
    throw new PermanentAiError(
      "OPENROUTER_API_KEY environment variable is not configured for Edge Functions"
    );
  }

  const systemPrompt = `You are Ghost AI, a Principal Systems Architect and Staff Software Engineer.
Your task is to analyze the provided system architecture diagram (nodes and connecting edges) and relevant collaborative chat context, and write a thorough, production-grade Technical Specification Document formatted in clean Markdown.

Your specification must include the following structured sections:

# Technical Specification: [System / Architecture Name]

## 1. Executive Summary & Objectives
- Overview of the system and primary business/technical problem it solves.
- Key requirements and non-functional goals (throughput, latency, availability, security).

## 2. High-Level Architecture
- Descriptive architectural diagram overview explaining topology (e.g. Microservices, Serverless, Event-Driven).
- Core architectural patterns (CQRS, Event Sourcing, Gateway Routing, BFF, etc.).

## 3. System Components & Service Catalog
- For each node in the diagram:
  - **Component Name** and Type (e.g. API Gateway, Microservice, Database, Queue, Auth Service).
  - Purpose & Core Responsibilities.
  - Recommended Technology Stack (e.g. Node.js / Go / Rust, Postgres / Redis, Kafka).
  - External Dependencies & Environment Config.

## 4. Communication Protocols & Data Flows
- Step-by-step trace of request, event, and background data lifecycles across the edges.
- Protocols used for each connection (e.g. HTTPS/REST, gRPC, WebSocket, SQL, AMQP/Kafka).
- API request/response contracts and event payloads.

## 5. Data Modeling & Storage Strategy
- Relational schema designs, document models, and caching strategies.
- Data persistence, replication, indexing, and backup policies.

## 6. Security, Authentication & Authorization
- Identity management, Token validation (JWT/OAuth2), RBAC policies.
- Network boundaries, TLS encryption in transit, and secret management.

## 7. Scalability, Resilience & Fault Tolerance
- Horizontal scaling strategy, load balancing, rate limiting.
- Dead-letter queues (DLQ), retry backoffs, circuit breakers, and disaster recovery.

## 8. Implementation Roadmap & Verification Plan
- Phased engineering milestones (Phase 1: Foundation, Phase 2: Core Services, Phase 3: Hardening & Launch).
- Acceptance criteria and automated testing strategy.

Provide a comprehensive, highly actionable technical document. Output ONLY the raw Markdown document without conversational preambles.`;

  const userContext = `Project / Architecture Name: "${projectName}"

Canvas Nodes (${nodes.length}):
${JSON.stringify(nodes, null, 2)}

Canvas Edges / Connections (${edges.length}):
${JSON.stringify(edges, null, 2)}

Recent Collaborative Discussion / Design Prompts:
${
  chatHistory.length > 0
    ? JSON.stringify(chatHistory, null, 2)
    : "No recent chat messages."
}
`;

  const modelsToTry = [
    OPENROUTER_MODEL_ID,
    "openrouter/free",
  ];

  let lastError: unknown = null;

  for (const modelId of modelsToTry) {
    if (signal.aborted) throw signal.reason;

    try {
      console.log(`[generate-spec] Requesting OpenRouter spec generation with model ${modelId}...`);
      const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${openRouterApiKey}`,
          "Content-Type": "application/json",
          "HTTP-Referer": "https://ghost-ai.dev",
          "X-Title": "Ghost AI Spec Generator",
        },
        body: JSON.stringify({
          model: modelId,
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userContext },
          ],
          temperature: 0.3,
        }),
        signal,
      });

      if (!res.ok) {
        const errText = await res.text();
        console.warn(`[generate-spec] Model ${modelId} returned HTTP ${res.status}:`, errText);
        const err = new Error(`OpenRouter ${modelId} returned ${res.status}: ${errText}`);
        Object.assign(err, { status: res.status });
        lastError = err;
        continue;
      }

      const data = (await res.json()) as {
        choices?: Array<{ message?: { content?: string } }>;
      };
      const rawText = data?.choices?.[0]?.message?.content;
      if (!rawText || typeof rawText !== "string" || !rawText.trim()) {
        console.warn(`[generate-spec] Model ${modelId} returned empty content.`);
        lastError = new Error("OpenRouter returned empty content");
        continue;
      }

      const specMarkdown = cleanMarkdownSpec(rawText);
      if (specMarkdown.length < 50) {
        console.warn(`[generate-spec] Model ${modelId} returned suspiciously short spec. Length: ${specMarkdown.length}`);
        lastError = new Error("Generated spec content was too short or empty");
        continue;
      }

      console.log(
        `[generate-spec] Successfully generated technical specification (${specMarkdown.length} chars) using ${modelId}`
      );
      return specMarkdown;
    } catch (err: unknown) {
      if (signal.aborted) throw signal.reason;
      console.warn(`[generate-spec] Error trying model ${modelId}:`, err);
      lastError = err;
    }
  }

  throw classifyError(
    lastError || new Error("All OpenRouter models failed to generate technical specification")
  );
}

/**
 * Executes the spec generation task:
 * 1. Validates task run and permissions.
 * 2. Emits real-time progress to project ai-status broadcast.
 * 3. Fetches canvas graph and generates Markdown spec via OpenRouter.
 * 4. Persists artifact in private 'specs' bucket at specs/{projectId}/{runId}.md.
 * 5. Idempotently inserts/updates project_specs metadata record.
 */
export async function processSpecTask(
  supabaseAdmin: SupabaseClient,
  context: SpecTaskContext
): Promise<string> {
  const { runId, projectId, userId, input, signal } = context;

  // 1. Validate task payload
  if (!runId || typeof runId !== "string") {
    throw new PermanentAiError("Missing or invalid runId in spec task context");
  }
  if (!projectId || typeof projectId !== "string") {
    throw new PermanentAiError("Missing or invalid projectId in spec task context");
  }

  // 2. Verify task run matches expected project, user, and kind
  const { data: taskRun, error: taskRunError } = await supabaseAdmin
    .from("task_runs")
    .select("id, project_id, user_id, kind, status")
    .eq("id", runId)
    .maybeSingle();

  if (taskRunError) {
    throw new TransientAiError(`Failed to fetch task run ${runId}: ${taskRunError.message}`);
  }

  if (!taskRun) {
    throw new PermanentAiError(`Task run ${runId} not found`);
  }

  if (taskRun.project_id !== projectId) {
    throw new PermanentAiError(
      `Task run ${runId} project mismatch: expected ${projectId}, found ${taskRun.project_id}`
    );
  }

  if (taskRun.kind !== "spec") {
    throw new PermanentAiError(
      `Task run ${runId} kind mismatch: expected 'spec', found '${taskRun.kind}'`
    );
  }

  let channel: RealtimeChannel | null = null;

  try {
    // 3. Establish project realtime broadcast channel
    channel = supabaseAdmin.channel(`project:${projectId}`, {
      config: {
        private: true,
        broadcast: { self: false, ack: false },
      },
    });
    await new Promise<void>((resolve, reject) => {
      const timeout = setTimeout(() => {
        reject(new TransientAiError("Timed out waiting for realtime channel subscription"));
      }, 8_000);

      channel.subscribe((status) => {
        if (status === "SUBSCRIBED") {
          clearTimeout(timeout);
          resolve();
          return;
        }
        if (status === "CHANNEL_ERROR" || status === "TIMED_OUT" || status === "CLOSED") {
          clearTimeout(timeout);
          reject(new TransientAiError(`Realtime channel subscription failed: ${status}`));
        }
      });
    });

    // 4. Broadcast start step
    await sendAiStatus(channel, {
      runId,
      projectId,
      status: "running",
      step: "start",
      message: "Starting technical specification generation...",
    });

    // 5. Gather canvas graph and chat context
    await sendAiStatus(channel, {
      runId,
      projectId,
      status: "running",
      step: "analyzing",
      message: "Analyzing architecture components, data flows, and requirements...",
    });

    // Resolve nodes and edges from input or fallback to storage snapshot
    let nodes = Array.isArray(input.nodes) ? input.nodes : [];
    let edges = Array.isArray(input.edges) ? input.edges : [];
    const chatHistory = Array.isArray(input.chatHistory) ? input.chatHistory : [];

    let projectName = "System Architecture";
    const { canvas: savedCanvas, projectName: resolvedName } = await fetchCurrentCanvas(
      supabaseAdmin,
      projectId
    );
    if (resolvedName) projectName = resolvedName;

    if (nodes.length === 0 && savedCanvas.nodes.length > 0) {
      nodes = savedCanvas.nodes;
    }
    if (edges.length === 0 && savedCanvas.edges.length > 0) {
      edges = savedCanvas.edges;
    }

    if (signal.aborted) throw signal.reason;

    // 6. Generate Markdown technical spec via OpenRouter
    await sendAiStatus(channel, {
      runId,
      projectId,
      status: "running",
      step: "generating",
      message: "Drafting complete technical specification document...",
    });

    const markdownSpec = await generateSpecWithOpenRouter(
      projectName,
      nodes,
      edges,
      chatHistory,
      signal
    );

    if (signal.aborted) throw signal.reason;

    // 7. Upload Markdown artifact to Supabase Storage at deterministic path
    // specs/{projectId}/{runId}.md (key inside 'specs' bucket: `${projectId}/${runId}.md`)
    const storageKey = `${projectId}/${runId}.md`;
    const fullStoragePath = `specs/${projectId}/${runId}.md`;

    const { error: uploadError } = await supabaseAdmin.storage
      .from(SPECS_BUCKET)
      .upload(storageKey, markdownSpec, {
        contentType: "text/markdown",
        upsert: true,
      });

    if (uploadError) {
      throw new TransientAiError(
        `Failed to upload generated spec to storage (${fullStoragePath}): ${uploadError.message}`
      );
    }

    // 8. Idempotently upsert project_specs metadata row
    const { error: dbError } = await supabaseAdmin
      .from("project_specs")
      .upsert(
        {
          task_run_id: runId,
          project_id: projectId,
          file_path: fullStoragePath,
          created_at: new Date().toISOString(),
        },
        { onConflict: "task_run_id" }
      );

    if (dbError) {
      throw new TransientAiError(
        `Failed to persist project_specs row for run ${runId}: ${dbError.message}`
      );
    }

    // 9. Broadcast terminal completion status
    await sendAiStatus(channel, {
      runId,
      projectId,
      status: "completed",
      step: "complete",
      message: "Technical specification generated and saved successfully.",
      text: "Technical specification generated successfully.",
    });

    return fullStoragePath;
  } catch (err: unknown) {
    const classified = classifyError(err);
    const isPermanent = classified instanceof PermanentAiError;

    const sanitizedMsg = isPermanent
      ? "Specification generation failed. Please try again."
      : "Specification generation is retrying after a temporary error.";

    if (channel) {
      await sendAiStatus(channel, {
        runId,
        projectId,
        status: isPermanent ? "failed" : "retrying",
        step: "failed",
        message: sanitizedMsg,
      });
    }

    throw classified;
  } finally {
    if (channel) {
      try {
        await supabaseAdmin.removeChannel(channel);
      } catch {
        // Ignore
      }
    }
  }
}
